import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '../..');

function loadEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return;
  const text = fs.readFileSync(filePath, 'utf8');
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim().replace(/^['"]|['"]$/g, '');
    if (!(key in process.env)) process.env[key] = value;
  }
}

loadEnvFile(path.join(rootDir, '.env'));
loadEnvFile(path.join(rootDir, '.env.presentation'));

export const presentationConfig = {
  rootDir,
  baseUrl: process.env.PRESENTATION_BASE_URL || 'http://localhost:5173',
  doctorPhone: process.env.PRESENTATION_DOCTOR_PHONE || '',
  doctorPassword: process.env.PRESENTATION_DOCTOR_PASSWORD || '',
  patientPhone: process.env.PRESENTATION_PATIENT_PHONE || '',
  patientPassword: process.env.PRESENTATION_PATIENT_PASSWORD || '',
  apiBaseUrl: process.env.PRESENTATION_API_BASE_URL || process.env.VITE_API_BASE_URL || '',
  startDevServer: process.env.PRESENTATION_START_DEV !== '0',
  screenshotsDir: path.join(rootDir, 'docs/presentation/screenshots'),
  outputDir: path.join(rootDir, 'docs/presentation'),
  tmpDir: path.join(rootDir, 'docs/presentation/tmp'),
  logoPath: path.join(rootDir, 'docs/presentation/zivan-mark.png'),
  browserChannel: process.env.PRESENTATION_BROWSER_CHANNEL || 'chrome',
  viewports: {
    desktop: { width: 1920, height: 1080 },
    tablet: { width: 1024, height: 1366 },
    mobile: { width: 390, height: 844 },
  },
};

/**
 * Manifest of required live captures.
 * Annotations are drawn in-page before screenshot (presentation callouts).
 */
export const screenshotManifest = [
  {
    id: 'login-page',
    file: 'login-page.png',
    route: '/login',
    auth: false,
    page: '/login',
    feature: 'Authentication',
    fullPage: true,
    captionFa: 'صفحه ورود پزشک با شماره موبایل و رمز عبور',
    captionEn: 'Doctor login with phone number and password',
  },
  {
    id: 'doctor-dashboard',
    file: 'doctor-dashboard.png',
    route: '/doctor',
    auth: true,
    page: '/doctor',
    feature: 'Doctor dashboard',
    fullPage: true,
    captionFa: 'داشبورد پزشک — آمار بیماران و دسترسی سریع',
    captionEn: 'Doctor dashboard — caseload stats and quick actions',
  },
  {
    id: 'patient-list',
    file: 'patient-list.png',
    route: '/doctor/patients',
    auth: true,
    page: '/doctor/patients',
    feature: 'Patient management',
    fullPage: true,
    captionFa: 'فهرست بیماران متصل و درخواست‌های در انتظار',
    captionEn: 'Linked patients and pending connection requests',
  },
  {
    id: 'patient-details',
    file: 'patient-details.png',
    route: '/doctor/patients',
    auth: true,
    page: '/doctor/patients (Patient overview drawer)',
    feature: 'Patient details',
    fullPage: false,
    open: 'patient-overview',
    captionFa: 'نمای کلی بیمار — اطلاعات، آمار پایبندی و برنامه‌ها',
    captionEn: 'Patient overview — demographics, adherence, programs',
  },
  {
    id: 'patient-history',
    file: 'patient-history.png',
    route: '/doctor/patients',
    auth: true,
    page: '/doctor/patients (Exercise history modal)',
    feature: 'Treatment follow-up',
    fullPage: false,
    open: 'patient-history',
    captionFa: 'تاریخچه انجام تمرین‌ها توسط بیمار',
    captionEn: 'Patient exercise completion history',
  },
  {
    id: 'assign-exercise-step1',
    file: 'assign-exercise-step1.png',
    route: '/doctor/patients',
    auth: true,
    page: '/doctor/patients (Assignment wizard · step 1)',
    feature: 'Exercise prescription',
    fullPage: false,
    open: 'assign-wizard-1',
    captionFa: 'مرحله ۱ تجویز — بازه زمانی و تناوب برنامه',
    captionEn: 'Prescription step 1 — period and cadence',
  },
  {
    id: 'assign-exercise-step2',
    file: 'assign-exercise-step2.png',
    route: '/doctor/patients',
    auth: true,
    page: '/doctor/patients (Assignment wizard · step 2)',
    feature: 'Exercise prescription',
    fullPage: false,
    open: 'assign-wizard-2',
    captionFa: 'مرحله ۲ تجویز — انتخاب تمرین از کتابخانه',
    captionEn: 'Prescription step 2 — select exercises from library',
  },
  {
    id: 'assign-exercise-step3',
    file: 'assign-exercise-step3.png',
    route: '/doctor/patients',
    auth: true,
    page: '/doctor/patients (Assignment wizard · step 3)',
    feature: 'Exercise prescription',
    fullPage: false,
    open: 'assign-wizard-3',
    captionFa: 'مرحله ۳ تجویز — ست، تکرار و توضیحات',
    captionEn: 'Prescription step 3 — sets, reps, and notes',
  },
  {
    id: 'treatment-plan',
    file: 'treatment-plan.png',
    route: '/doctor/patients',
    auth: true,
    page: '/doctor/patients (Programs in overview drawer)',
    feature: 'Treatment plan management',
    fullPage: false,
    open: 'treatment-plan',
    captionFa: 'مدیریت برنامه‌های درمانی فعال بیمار',
    captionEn: 'Active treatment programs for the patient',
  },
  {
    id: 'exercise-management',
    file: 'exercise-management.png',
    route: '/doctor/exercises',
    auth: true,
    page: '/doctor/exercises',
    feature: 'Exercise library',
    fullPage: true,
    captionFa: 'کتابخانه تمرینات شخصی پزشک',
    captionEn: 'Doctor personal exercise library',
  },
  {
    id: 'exercise-catalog',
    file: 'exercise-catalog.png',
    route: '/doctor/exercises',
    auth: true,
    page: '/doctor/exercises (Catalog picker)',
    feature: 'Exercise library',
    fullPage: false,
    open: 'exercise-catalog',
    captionFa: 'افزودن تمرین از فهرست مرکزی',
    captionEn: 'Add exercises from the central catalog',
  },
  {
    id: 'exercise-details',
    file: 'exercise-details.png',
    route: '/doctor/exercises',
    auth: true,
    page: '/doctor/exercises (Edit texts modal)',
    feature: 'Exercise library',
    fullPage: false,
    open: 'exercise-form',
    captionFa: 'ویرایش توضیحات و دستورالعمل تمرین',
    captionEn: 'Edit exercise description and instructions',
  },
  // Patient panel
  {
    id: 'patient-login-page',
    file: 'patient-login-page.png',
    route: '/login',
    auth: false,
    page: '/login (patient credentials)',
    feature: 'Patient authentication',
    fullPage: true,
    captionFa: 'ورود بیمار به سامانه',
    captionEn: 'Patient login',
  },
  {
    id: 'patient-dashboard',
    file: 'patient-dashboard.png',
    route: '/patient',
    auth: true,
    role: 'patient',
    page: '/patient',
    feature: 'Patient dashboard',
    fullPage: true,
    captionFa: 'داشبورد بیمار — پیشرفت امروز و تمرین‌ها',
    captionEn: 'Patient dashboard — today progress and exercises',
  },
  {
    id: 'patient-my-exercises',
    file: 'patient-my-exercises.png',
    route: '/patient/exercises',
    auth: true,
    role: 'patient',
    page: '/patient/exercises',
    feature: 'Assigned exercises',
    fullPage: true,
    captionFa: 'تمرین‌های تجویزشده امروز بیمار',
    captionEn: 'Patient assigned exercises for today',
  },
  {
    id: 'patient-exercise-details',
    file: 'patient-exercise-details.png',
    route: '/patient/exercises',
    auth: true,
    role: 'patient',
    page: '/patient/exercises (video / instructions)',
    feature: 'Exercise details',
    fullPage: false,
    captionFa: 'جزئیات و ویدیوی تمرین برای بیمار',
    captionEn: 'Patient exercise details and video',
  },
  {
    id: 'patient-treatment-plan',
    file: 'patient-treatment-plan.png',
    route: '/patient/exercises',
    auth: true,
    role: 'patient',
    page: '/patient/exercises (today plan)',
    feature: 'Patient treatment plan',
    fullPage: true,
    captionFa: 'برنامه درمانی روزانه بیمار',
    captionEn: 'Patient daily treatment plan',
  },
  {
    id: 'patient-workout-session',
    file: 'patient-workout-session.png',
    route: '/patient/exercises',
    auth: true,
    role: 'patient',
    page: '/patient/exercises (workout session)',
    feature: 'Workout session',
    fullPage: false,
    captionFa: 'جلسه انجام تمرین توسط بیمار',
    captionEn: 'Patient workout session overlay',
  },
  {
    id: 'patient-progress',
    file: 'patient-progress.png',
    route: '/patient/progress',
    auth: true,
    role: 'patient',
    page: '/patient/progress',
    feature: 'Patient progress',
    fullPage: true,
    captionFa: 'صفحه پیشرفت و پایبندی بیمار',
    captionEn: 'Patient progress and adherence',
  },
  {
    id: 'patient-doctors',
    file: 'patient-doctors.png',
    route: '/patient/doctors',
    auth: true,
    role: 'patient',
    page: '/patient/doctors',
    feature: 'Patient doctors',
    fullPage: true,
    captionFa: 'پزشکان من در پنل بیمار',
    captionEn: 'Patient linked doctors',
  },
];
