import { theme, type ThemeConfig } from 'antd';

/** Energetic Dark — bold rehab coach on deep navy surfaces */
export const PHISIO_COLORS = {
  primary: '#2dd4bf',
  primaryHover: '#14b8a6',
  primarySoft: 'rgba(45, 212, 191, 0.12)',
  primaryMuted: 'rgba(45, 212, 191, 0.24)',
  coral: '#f97316',
  coralSoft: 'rgba(249, 115, 22, 0.16)',
  mint: '#a7f3d0',
  success: '#34d399',
  warning: '#fbbf24',
  error: '#f87171',
  info: '#38bdf8',
  background: '#0b1220',
  backgroundElevated: '#111827',
  surface: '#1e293b',
  surfaceHover: '#243044',
  surfaceElevated: '#1a2332',
  text: '#f8fafc',
  textSecondary: '#94a3b8',
  textMuted: '#64748b',
  border: 'rgba(148, 163, 184, 0.18)',
  borderGlow: 'rgba(45, 212, 191, 0.45)',
} as const;

export const PHISIO_SHADOWS = {
  sm: '0 2px 8px rgba(0, 0, 0, 0.35)',
  md: '0 8px 24px rgba(0, 0, 0, 0.45)',
  lg: '0 16px 48px rgba(0, 0, 0, 0.55)',
  card: '0 4px 20px rgba(0, 0, 0, 0.4)',
  glowTeal: '0 0 24px rgba(45, 212, 191, 0.25)',
  glowCoral: '0 0 24px rgba(249, 115, 22, 0.22)',
} as const;

export const phisioTheme: ThemeConfig = {
  algorithm: theme.darkAlgorithm,
  token: {
    colorPrimary: PHISIO_COLORS.primary,
    colorPrimaryHover: PHISIO_COLORS.primaryHover,
    colorPrimaryBg: PHISIO_COLORS.primarySoft,
    colorPrimaryBgHover: PHISIO_COLORS.primaryMuted,
    colorSuccess: PHISIO_COLORS.success,
    colorWarning: PHISIO_COLORS.warning,
    colorError: PHISIO_COLORS.error,
    colorInfo: PHISIO_COLORS.info,
    colorText: PHISIO_COLORS.text,
    colorTextSecondary: PHISIO_COLORS.textSecondary,
    colorTextTertiary: PHISIO_COLORS.textMuted,
    colorBgLayout: PHISIO_COLORS.background,
    colorBgContainer: PHISIO_COLORS.surface,
    colorBgElevated: PHISIO_COLORS.surfaceElevated,
    colorBorder: PHISIO_COLORS.border,
    colorBorderSecondary: PHISIO_COLORS.border,
    borderRadius: 14,
    borderRadiusLG: 18,
    borderRadiusSM: 10,
    fontFamily: 'IRANSans, Tahoma, sans-serif',
    fontSize: 15,
    fontSizeHeading1: 30,
    fontSizeHeading2: 24,
    fontSizeHeading3: 20,
    fontSizeHeading4: 17,
    fontSizeHeading5: 15,
    lineHeight: 1.6,
    controlHeight: 46,
    controlHeightLG: 50,
    controlHeightSM: 38,
    boxShadow: PHISIO_SHADOWS.md,
    boxShadowSecondary: PHISIO_SHADOWS.sm,
    boxShadowTertiary: PHISIO_SHADOWS.card,
    motionDurationMid: '0.22s',
  },
  components: {
    Layout: {
      headerBg: PHISIO_COLORS.backgroundElevated,
      siderBg: PHISIO_COLORS.backgroundElevated,
      bodyBg: PHISIO_COLORS.background,
      headerHeight: 64,
      headerPadding: '0 20px',
    },
    Card: {
      borderRadiusLG: 18,
      paddingLG: 22,
      colorBgContainer: PHISIO_COLORS.surface,
      colorBorderSecondary: PHISIO_COLORS.border,
    },
    Button: {
      controlHeight: 46,
      controlHeightLG: 50,
      borderRadius: 14,
      borderRadiusLG: 16,
      primaryShadow: PHISIO_SHADOWS.glowTeal,
      fontWeight: 600,
    },
    Input: {
      controlHeight: 46,
      controlHeightLG: 50,
      borderRadius: 14,
      colorBgContainer: PHISIO_COLORS.backgroundElevated,
      activeBorderColor: PHISIO_COLORS.primary,
      hoverBorderColor: PHISIO_COLORS.borderGlow,
      activeShadow: `0 0 0 3px ${PHISIO_COLORS.primaryMuted}`,
    },
    Select: {
      controlHeight: 46,
      borderRadius: 14,
      colorBgContainer: PHISIO_COLORS.backgroundElevated,
    },
    Form: {
      labelColor: PHISIO_COLORS.text,
      labelFontSize: 14,
      itemMarginBottom: 20,
    },
    Menu: {
      itemHeight: 48,
      itemBorderRadius: 12,
      itemSelectedColor: PHISIO_COLORS.primary,
      itemSelectedBg: PHISIO_COLORS.primarySoft,
      itemHoverBg: PHISIO_COLORS.primarySoft,
      darkItemBg: 'transparent',
      darkSubMenuItemBg: 'transparent',
    },
    Table: {
      borderRadius: 14,
      headerBg: PHISIO_COLORS.backgroundElevated,
      headerColor: PHISIO_COLORS.text,
      headerSplitColor: 'transparent',
      rowHoverBg: PHISIO_COLORS.primarySoft,
      colorBgContainer: PHISIO_COLORS.surface,
    },
    Modal: {
      borderRadiusLG: 18,
      contentBg: PHISIO_COLORS.surface,
      headerBg: PHISIO_COLORS.surface,
    },
    Drawer: {
      borderRadiusLG: 18,
      colorBgElevated: PHISIO_COLORS.backgroundElevated,
    },
    Segmented: {
      borderRadius: 12,
      itemSelectedBg: PHISIO_COLORS.surface,
      itemSelectedColor: PHISIO_COLORS.primary,
      trackBg: PHISIO_COLORS.backgroundElevated,
    },
    Tag: {
      borderRadiusSM: 8,
    },
    Statistic: {
      titleFontSize: 13,
      contentFontSize: 30,
    },
    Progress: {
      defaultColor: PHISIO_COLORS.primary,
      remainingColor: PHISIO_COLORS.backgroundElevated,
    },
    Alert: {
      borderRadiusLG: 14,
    },
    Empty: {
      colorTextDescription: PHISIO_COLORS.textSecondary,
    },
    Typography: {
      titleMarginBottom: 0,
      titleMarginTop: 0,
    },
    Radio: {
      buttonBg: PHISIO_COLORS.backgroundElevated,
      buttonCheckedBg: PHISIO_COLORS.primarySoft,
      buttonSolidCheckedBg: PHISIO_COLORS.primary,
      borderRadius: 12,
    },
    Steps: {
      iconSize: 30,
    },
    Dropdown: {
      colorBgElevated: PHISIO_COLORS.surface,
    },
  },
};
